# Generated by Django 5.1.4 on 2025-01-31 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersurvey',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='survey_photos/'),
        ),
    ]
