# Generated by Django 5.1.4 on 2025-01-31 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_alter_usersurvey_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersurvey',
            name='photo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
